import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'



const inter = Inter({ subsets: ['latin'] })
if (typeof window !== 'undefined') {
  require('bootstrap/dist/js/bootstrap.min.js');
}


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div id="demo" className={`${styles.body} carousel slide`} data-bs-ride="carousel">

        {/* Cada uno de los botones representa cada una de 
        las imagenes como si fuera en una lista empieza en 0 */}
        {/*"carousel-indicators" son los botones que se ven en la parrte inferior*/} 
        <div className={`${styles['carousel-indicators']} carousel-indicators`} > 
          <button type="button" data-bs-target="#demo" data-bs-slide-to="0" className='active'></button>
          <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
          <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
          <button type="button" data-bs-target="#demo" data-bs-slide-to="3"></button>
          <button type="button" data-bs-target="#demo" data-bs-slide-to="4"></button>
          <button type="button" data-bs-target="#demo" data-bs-slide-to="5"></button>
        </div>
        
        <div className="carousel-inner"> {/* "carousel-inner" ingresa las diapositivas */}
          <div className="carousel-item active">
            <header className={`${styles.imagenes} ${styles.imagen1}`}>
              <div className={`${styles.contenedor}`}>
                <div className={`${styles.barra}`}>
                  <a className={`${styles.logo} ${styles.a}`} href='/'> 
                    <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
                  </a> 
                  <nav className={`${styles.navegacion}`}>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Nosotros</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Productos</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Contacto</a>
                  </nav>
                </div> {/* .barra */}
              </div> {/* .contenedor */}
              <div className={`${styles.header__texto}`}>
                  <h2 className={`${styles.h2}`}>Lengua de Suegra</h2>
                  <p className={`${styles.p}`}>Lengua de Suegra</p>
              </div>
            </header>
          </div> {/* Primer diapositiva .carousel-item .active */}

          <div className="carousel-item">
            <header className={`${styles.imagenes} ${styles.imagen2}`}>
              <div className={`${styles.contenedor}`}>
                <div className={`${styles.barra}`}>
                  <a className={`${styles.logo} ${styles.a}`} href='/'> 
                    <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
                  </a> 
                  <nav className={`${styles.navegacion}`}>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Nosotros</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Productos</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Contacto</a>
                  </nav>
                </div> {/* .barra */}
              </div> {/* .contenedor */}
              <div className={`${styles.header__texto}`}>
                  <h2 className={`${styles.h2}`}>Coral Bells</h2>
                  <p className={`${styles.p}`}>Coral Bells</p>
              </div>
            </header>
          </div> {/* Segunda diapositiva .carousel-item */}

          <div className="carousel-item">
            <header className={`${styles.imagenes} ${styles.imagen3}`}>
              <div className={`${styles.contenedor}`}>
                <div className={`${styles.barra}`}>
                  <a className={`${styles.logo} ${styles.a}`} href='/'> 
                    <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
                  </a> 
                  <nav className={`${styles.navegacion}`}>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Nosotros</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Productos</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Contacto</a>
                  </nav>
                </div> {/* .barra */}
              </div> {/* .contenedor */}
              <div className={`${styles.header__texto}`}>
                  <h2 className={`${styles.h2}`}>Hiedra del Diablo</h2>
                  <p className={`${styles.p}`}>Hiedra del Diablo</p>
              </div>
            </header>
          </div> {/* Tercer diapositiva .carousel-item */}

          <div className="carousel-item">
            <header className={`${styles.imagenes} ${styles.imagen4}`}>
              <div className={`${styles.contenedor}`}>
                <div className={`${styles.barra}`}>
                  <a className={`${styles.logo} ${styles.a}`} href='/'> 
                    <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
                  </a> 
                  <nav className={`${styles.navegacion}`}>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Nosotros</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Productos</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Contacto</a>
                  </nav>
                </div> {/* .barra */}
              </div> {/* .contenedor */}
              <div className={`${styles.header__texto}`}>
                  <h2 className={`${styles.h2}`}>Palma de Madagscar</h2>
                  <p className={`${styles.p}`}>Palma de Madagascar</p>
              </div>
            </header>
          </div> {/* Cuarta diapositiva .carousel-item */}

          <div className="carousel-item">
            <header className={`${styles.imagenes} ${styles.imagen5}`}>
              <div className={`${styles.contenedor}`}>
                <div className={`${styles.barra}`}>
                  <a className={`${styles.logo} ${styles.a}`} href='/'> 
                    <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
                  </a> 
                  <nav className={`${styles.navegacion}`}>
                    <a href='#' className={`${styles.navegacion__enlace}`}>Nosotros</a>
                    <a href='#' className={`${styles.navegacion__enlace}`}>Productos</a>
                    <a href='#' className={`${styles.navegacion__enlace}`}>Contacto</a>
                  </nav>
                </div> {/* .barra */}
              </div> {/* .contenedor */}
              <div className={`${styles.header__texto}`}>
                  <h2 className={`${styles.h2}`}>Planta de Hierro</h2>
                  <p className={`${styles.p}`}>Planta de Hierro</p>
              </div>
            </header>
          </div> {/* Quinta diapositiva .carousel-item .active */}

          <div className="carousel-item">
            <header className={`${styles.imagenes} ${styles.imagen6}`}>
              <div className={`${styles.contenedor}`}>
                <div className={`${styles.barra}`}>
                  <a className={`${styles.logo} ${styles.a}`} href='/'> 
                    <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
                  </a> 
                  <nav className={`${styles.navegacion}`}>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Nosotros</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Productos</a>
                    <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Contacto</a>
                  </nav>
                </div> {/* .barra */}
              </div> {/* .contenedor */}
              <div className={`${styles.header__texto}`}>
                  <h2 className={`${styles.h2}`}>Verde para Siempre</h2>
                  <p className={`${styles.p}`}>Verde para Siempre</p>
              </div>
            </header>
          </div> {/* Sexta diapositiva .carousel-item .active */}
        </div> {/* .carousel-inner */}
        <button className="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
            <span className="carousel-control-prev-icon"></span>
        </button>
        <button className="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
            <span className="carousel-control-next-icon"></span>
        </button>
      </div> {/* /Aqui se termina el carrusel .carousel y .slide/ */}

      <div className={`${styles.contenedor} ${styles.contenido__principal} `}>
        
          <article className={`${styles.entrada}`}>
              <div className={`${styles.margen}`}>
                <img className={`${styles.imagen}`} src="/img/ImagenX.jpg" alt='Imagenx' />
              </div>
          </article>

          <article className={`${styles.entrada}`}>
              <div className={`${styles.margen}`}>
                <img className={`${styles.imagen}`} src="/img/ImagenX.jpg" alt='Imagenx'/>
              </div>
          </article>

          <article className={`${styles.entrada} ${styles.grid3}`}>
              <div className={`${styles.margen} `} >
                <img className={`${styles.imagen}`} src="/img/ImagenX.jpg" alt='Imagenx'/>
              </div>
          </article>
       
      </div>

      <footer className={`${styles.footer}`}>
        <div className={`${styles.contenedor}`}>
          <div className={`${styles.barra2}`}>
              <a className={`${styles.logo} ${styles.a}`}  href='/'>
                  <h1 className={`${styles.logo__nombre} ${styles.centrar__texto} ${styles.h1}`}>Titulo</h1>
              </a>
              <nav className={`${styles.navegacion}`}>
                  <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Nosotros</a>
                  <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Productos</a>
                  <a href='#' className={`${styles.navegacion__enlace} ${styles.a}`}>Contacto</a> 
              </nav>
          </div>
        </div>
      </footer>
     
      
      
    </>
  )
}
if (typeof document !== 'undefined') {
  Home()
}
